name: GitHub Actions Demo
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  fetchLanguages:
    name: Fetch Languages in Repo
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.get-present-languages.outputs.LANGUAGES }}
      go: ${{ steps.get-present-languages.outputs.GO }}
      java: ${{ steps.get-present-languages.outputs.JAVA }}
      javascript-typescript: ${{ steps.get-present-languages.outputs.JAVASCRIPT_TYPESCRIPT }}
      python: ${{ steps.get-present-languages.outputs.PYTHON }}
    steps:
      - name: Get Present Languages
        id: get-present-languages
        run: echo "LANGUAGES=$(curl -s ${{ github.event.repository.languages_url }} | jq -r 'keys[]')" >> $GITHUB_OUTPUT
  parsePython:
    name: Parse Python Maps
    runs-on: ubuntu-latest
    container:
      image: 'us-docker.pkg.dev/plumbr/sourcefield-public/lsif-python-pyright:e854776'
    needs: [fetchLanguages]
    if: contains(needs.fetchLanguages.outputs.languages, 'Python')
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Fetch history back to merge-base
        run: |
          commits=${{ github.event.pull_request.commits }}
          if [[ -n "$commits" ]]; then
            git fetch --depth="$(( commits + 1 ))"
          fi
      - name: Get merge-base
        run: echo "MERGE_BASE=$(git merge-base ${{ github.base_ref }} ${{ github.sha }})" >> $GITHUB_ENV
      - name: Run LSIF parser on base ref
        run: |
          git checkout ${{ env.MERGE_BASE }}
          lsif-python index --project-name="${{ github.repository }}" --output="output.json"
          cat output.json
      - name: Run LSIF parser on head ref
        run: |
          git checkout ${{ github.sha }}
          lsif-python index --project-name="${{ github.repository }}" --output="output.json"
          cat output.json
#      - name: LSIF Parser
#        uses: docker://us-docker.pkg.dev/plumbr/sourcefield-public/lsif-python-pyright:e854776
#        with:
#          entrypoint: /bin/ls
#          args: -lah /github/workspace
#      - name: Run LSIF parser
#        uses: addnab/docker-run-action@v3
#        with:
#          image: us-docker.pkg.dev/plumbr/sourcefield-public/lsif-python-pyright:e854776
#          options: -v ${{ github.workspace }}:/github/workspace
#          run: |
#            ls -lah /github/workspace
#            cd /github/workspace
#            lsif-python index --project-name="${{ github.repository }}" --output="output.json"
#            head output.json

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Hello world from Docker
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'awesome'
      - uses: rmacklin/fetch-through-merge-base@v0
        with:
          base_ref: main
          head_ref: ${{ github.sha }}
      # now we've fetched commits through the merge-base of the source branch
      # and target branch of the pull request, so we can do things like:
      - run: echo "MERGE_BASE=$(git merge-base main ${{ github.sha }})" >> $GITHUB_ENV
      - run: echo "merge base = ${{ env.MERGE_BASE }}"
      - run: echo "HEAD = ${{ github.event.pull_request.head.sha }}"
      - run: git log --oneline main..
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Find changed files
        run: |
          echo 'LS_DIFF<<EOF' >> $GITHUB_ENV
          git diff --name-only main...${{ github.sha }} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Update or create PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Changed files:
            ```
            ${{ env.LS_DIFF }}
            ```
            Commit: ${{ github.sha }}
            <details><summary>Event payload</summary>
            
            ```json
            ${{ toJson(github.event) }}
            ```
            
            ```
            ${{ env.EVENT_CONTENTS }}
            ```
            </details>
          comment_includes: 'Changed files:'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
