name: GitHub Actions Demo
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Hello world from Docker
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'awesome'
      - uses: rmacklin/fetch-through-merge-base@v0
        with:
          base_ref: main
          head_ref: ${{ github.sha }}
      # now we've fetched commits through the merge-base of the source branch
      # and target branch of the pull request, so we can do things like:
      - run: echo "MERGE_BASE=$(git merge-base main ${{ github.sha }})" >> $GITHUB_ENV
      - run: echo "merge base = ${{ env.MERGE_BASE }}"
      - run: echo "HEAD = ${{ github.event.pull_request.head.sha }}"
      - run: git log --oneline main..
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Languages = $(curl -s ${{ github.event.repository.languages_url }})"
      - name: Find changed files
        run: |
          echo 'LS_DIFF<<EOF' >> $GITHUB_ENV
          git diff --name-only main...${{ github.sha }} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Update or create PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Changed files:
            ```
            ${{ env.LS_DIFF }}
            ```
            Commit: ${{ github.sha }}
            <details><summary>Event payload</summary>
            
            ```json
            ${{ toJson(github.event) }}
            ```
            
            ```
            ${{ env.EVENT_CONTENTS }}
            ```
            </details>
          comment_includes: 'Changed files:'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
